### ISSUE TITLE
webserv todo

### ISSUE THREAD

**Issue by aLVINlEE9** [keonwoo98/webserv#108]
- [x] static 으로 log write할 파일 fd 값 저장
- [x] event 확인할때 맨앞에서 webserv에 저장된 log write fd 값과 event.ident와 비교 -> 에러메세지 write
- [x] error log 남길때 udata대신 logger 클래스 작성 -> 버퍼 저장 
- [x] error log 끝날땐 그냥 자신 event delete해주면됨
- [x] throw 로 받은거 add event (error_log_fd랑 send_response 둘다 해줌)

**Comment by minjune8506** [comment]
log 기능은 제가 구현할게요
